---
- name: Add kube-prometheus-stack chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Update helm repo
  ansible.builtin.command: helm repo update

- name: Deploy kube-prometheus-stack chart inside {{ prometheus_stack_namespace }} namespace with values
  kubernetes.core.helm:
    kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
    name: "{{ prometheus_stack_release_name }}"
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: "{{ prometheus_stack_namespace }}"
    create_namespace: yes
    force: yes
    values:
      grafana:
        image:
          repository: grafana/grafana
        ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - "{{ grafana_ingress_host }}"
            path: /
            pathType: Prefix
        additionalDataSources:
          - name: Loki
            access: proxy
            type: loki
            url: http://logging-loki.logging:3100
      kubeControllerManager:
        service:
          targetPort: 10257
        serviceMonitor:
          https: true
          insecureSkipVerify: true
      kubeScheduler:
        service:
          targetPort: 10259
        serviceMonitor:
          https: true
          insecureSkipVerify: true
      kubeEtcd:
        service:
          targetPort: 2381
      alertmanager:
        ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - "{{ alertmanager_ingress_host }}"
            path:
              - /
            pathType: Prefix

- name: Wait for kube-prometheus-stack pods become ready
  ansible.builtin.command: "kubectl wait --namespace={{ prometheus_stack_namespace }} --for=condition=Ready --all pods --timeout=600s"
