- block:
  - name: 配置 etcd.sh 到/etc/profile.d/
    template:
      src: "{{ inventory_dir }}/roles/01-preinstall/templates/etcd.sh.j2"
      dest: "{{ profile_dir }}/etcd.sh"
      owner: root
      group: root
      mode: 0755

  - name: 配置 etcd 备份脚本
    template:
      src: "{{ inventory_dir }}/roles/01-preinstall/templates/etcd_cron.sh.j2"
      dest: "/usr/local/bin/etcd_cron.sh"
      owner: root
      group: root
      mode: 0755
  when: inventory_hostname in (groups['kube_masters'] | difference(groups['delete_masters']) | unique)
