---
- name: 安装 kube-proxy
  when:
  - skip_kube_proxy | bool
  block:
  - name: 创建 kube-proxy 组件配置文件目录
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: 0644
    with_items:
    - "{{ addons_dir }}/kube-proxy"

  - name: 渲染 kube-proxy 配置文件
    ansible.builtin.template:
      src: "{{ item.src }}.j2"
      dest: "{{ item.dest }}"
      mode: "0644"
    with_items:
    - { src: "kube-proxy/kubeproxy-cm.yml", dest: "{{ addons_dir }}/kube-proxy/kubeproxy-cm.yml" }
    - { src: "kube-proxy/kubeproxy-ds.yml", dest: "{{ addons_dir }}/kube-proxy/kubeproxy-ds.yml" }
