---
- name: Cluster kernel reset
  hosts: kube_cluster
  become: true
  gather_facts: true
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
  - { role: 99-cluster-reset, reset_kernel_module: false }

- name: Cluster component reset
  hosts: kube_cluster
  become: true
  gather_facts: true
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
  - { role: 99-cluster-reset, reset_k8s: true }

- name: Cluster etcd reset
  hosts: kube_masters
  become: true
  gather_facts: true
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
  - { role: 99-cluster-reset, reset_etcd: true }
