---
- name: Reset kernel module
  when: reset_kernel_module|default(false)
  ansible.builtin.include_tasks: reset-kernel-module.yml

- name: Reset Kubernetes cluster
  when: reset_k8s|default(false)
  ansible.builtin.include_tasks: reset-k8s.yml

- name: Reset etcd cluster
  when: reset_etcd|default(false)
  ansible.builtin.include_tasks: reset-etcd.yml
