---
- name: 停用systemd自动加载模块服务
  ansible.builtin.systemd:
    name: systemd-modules-load
    state: stopped
    enabled: false
  register: stop_modules_result
  failed_when: stop_modules_result.failed

- name: 删除内核模块开机加载配置
  ansible.builtin.file:
    path: /etc/modules-load.d/10-k8s-modules.conf
    state: absent

- name: 获取当前内核版本
  changed_when: true
  ansible.builtin.command: "uname -r"
  register: get_kernel_version

- name: 设置内核版本参数
  ansible.builtin.set_fact:
    set_fact_kernel_version: "{{ get_kernel_version.stdout.split('-')[0] }}"

- name: 设置 nf_conntrack 模块名
  when: "set_fact_kernel_version is version('4.19', '>=')"
  ansible.builtin.set_fact:
    nf_conntrack: "nf_conntrack"

- name: 设置 nf_conntrack_ipv4 模块名
  when: "set_fact_kernel_version is version('4.19', '<')"
  ansible.builtin.set_fact:
    nf_conntrack: "nf_conntrack_ipv4"

- name: 卸载已加载的内核模块
  community.general.modprobe:
    name: "{{ item }}"
    state: absent
  with_items:
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - ip_vs_lc
    - ip_vs_wlc
    - ip_vs_lblc
    - ip_vs_lblcr
    - ip_vs_dh
    - ip_vs_fo
    - ip_vs_nq
    - ip_vs_sed
    - ip_vs_ftp
    - "{{ nf_conntrack }}"
    - sunrpc
  failed_when: false

- name: 删除内核优化
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "95-k8s-sysctl.conf"

- name: 重新加载系统参数
  changed_when: true
  ansible.builtin.command: "sysctl --system"
