---
- name: 清理 kubectl completion env
  ansible.builtin.lineinfile:
    dest: "/home/{{ item }}/.bashrc"
    state: absent
    regexp: 'kubectl completion'
  with_items:
  - "{{ normal_user }}"

- name: 删除 kubeconfig 认证文件
  ansible.builtin.file:
    path: "/home/{{ item }}/.kube"
    state: absent
  with_items:
  - "{{ normal_user }}"
