---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "172.21.139.219"
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    network-plugin: cni
    root-dir: "/var/lib/kubelet"
    hostname-override: "172.21.139.219"
    pod-infra-container-image: "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2"
  criSocket: "/var/run/dockershim.sock"
  name: "172.21.139.219"
  taints: []
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  description: "kubeadm bootstrap token"
  token: "abcdef.0123456789abcdef"
  ttl: "24h0m0s"
  usages:
  - signing
  - authentication
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: "v1.18.20"
clusterName: "kubernetes"
controlPlaneEndpoint: "apiserver.k8s.local:6443"
certificatesDir: "/etc/kubernetes/pki"
etcd:
  local:
    serverCertSANs:
    - localhost
    - 127.0.0.1
    peerCertSANs:
    - localhost
    - k8s.etcd.local
    - etcd.local.com
    - 127.0.0.1
imageRepository: "registry.cn-hangzhou.aliyuncs.com/google_containers"
imageTag: "3.4.3-0"
networking:
  dnsDomain: "cluster.local"
  podSubnet: "172.30.0.0/16"
  serviceSubnet: "172.31.0.0/16"
apiServer:
  certSANs:
  - localhost
  - kubernetes
  - kubernetes.default
  - kubernetes.default.svc
  - kubernetes.default.svc.cluster
  - kubernetes.default.svc.cluster.local
  - apiserver.k8s.local
  - apiserver.local.com
  - 127.0.0.1
  - 172.31.0.1
  - 192.168.100.100
  - 11.11.11.11
  - 2.2.2.2
  extraArgs:
    enable-admission-plugins: "NamespaceExists,NamespaceLifecycle,LimitRanger,ServiceAccount,Priority,DefaultTolerationSeconds,DefaultStorageClass,PersistentVolumeClaimResize,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction,PersistentVolumeLabel"
    feature-gates: "RotateKubeletServerCertificate=true"
    audit-log-maxbackup: "10"
    requestheader-client-ca-file: "/etc/kubernetes/pki/front-proxy-ca.crt"
    watch-cache-sizes: "node#100,pod#1000"
    encryption-provider-config: "/etc/kubernetes/enc/secrets-encryption.yaml"
    requestheader-extra-headers-prefix: "X-Remote-Extra-"
    kubelet-client-key: "/etc/kubernetes/pki/apiserver-kubelet-client.key"
    proxy-client-cert-file: "/etc/kubernetes/pki/front-proxy-client.crt"
    max-mutating-requests-inflight: "500"
    kubelet-client-certificate: "/etc/kubernetes/pki/apiserver-kubelet-client.crt"
    api-audiences: "api,istio-ca"
    requestheader-allowed-names: ""
    audit-log-truncate-enabled: "true"
    audit-log-maxsize: "100"
    proxy-client-key-file: "/etc/kubernetes/pki/front-proxy-client.key"
    apiserver-count: "1"
    audit-log-path: "/var/log/kubernetes/audit/apiserver_audit.log"
    profiling: "false"
    tls-cipher-suites: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
    requestheader-username-headers: "X-Remote-User"
    enable-bootstrap-token-auth: "true"
    audit-policy-file: "/etc/kubernetes/audit/policy.yaml"
    max-requests-inflight: "1500"
    service-account-issuer: "https://kubernetes.default.svc.cluster.local"
    enable-aggregator-routing: "true"
    runtime-config=api/all: "true"
    requestheader-group-headers: "X-Remote-Group"
    allow-privileged: "true"
    kubelet-certificate-authority: "/etc/kubernetes/pki/ca.crt"
    audit-log-maxage: "30"
    v: "2"
    service-node-port-range: "30000-32767"
    service-account-signing-key-file: "/etc/kubernetes/pki/sa.key"
  extraVolumes:
    - hostPath: "/etc/localtime"
      mountPath: "/etc/localtime"
      pathType: File
      readOnly: true
      name: localtime
    - hostPath: "/etc/kubernetes/audit"
      mountPath: "/etc/kubernetes/audit"
      pathType: DirectoryOrCreate
      readOnly: true
      name: audit-policy
    - hostPath: "/var/log/kubernetes/audit"
      mountPath: "/var/log/kubernetes/audit"
      pathType: DirectoryOrCreate
      name: audit-logs
    - name: secrets-encryption
      hostPath: /etc/kubernetes/enc/secrets-encryption.yaml
      mountPath: /etc/kubernetes/enc/secrets-encryption.yaml
      readOnly: True
controllerManager:
  extraArgs:
    bind-address: 127.0.0.1
    feature-gates: "RotateKubeletServerCertificate=true"
    profiling: "false"
    horizontal-pod-autoscaler-initial-readiness-delay: "30s"
    requestheader-allowed-names: ""
    concurrent-gc-syncs: "30"
    concurrent-service-syncs: "2"
    attach-detach-reconcile-sync-period: "1m0s"
    requestheader-client-ca-file: "/etc/kubernetes/pki/front-proxy-ca.crt"
    kube-api-qps: "100"
    concurrent-deployment-syncs: "10"
    horizontal-pod-autoscaler-cpu-initialization-period: "5m0s"
    service-cluster-ip-range: "172.31.0.0/16"
    kube-api-burst: "100"
    concurrent-replicaset-syncs: "10"
    controllers: "*,bootstrapsigner,tokencleaner"
    cluster-name: "kubernetes"
    allocate-node-cidrs: "true"
    horizontal-pod-autoscaler-downscale-stabilization: "15m"
    cluster-cidr: "172.30.0.0/16"
    horizontal-pod-autoscaler-sync-period: "30s"
    horizontal-pod-autoscaler-tolerance: "0.1"
  extraVolumes:
    - hostPath: "/etc/localtime"
      mountPath: "/etc/localtime"
      pathType: File
      readOnly: true
      name: localtime
scheduler:
  extraArgs:
    bind-address: 127.0.0.1
    feature-gates: "RotateKubeletServerCertificate=true"
    profiling: "false"
    requestheader-client-ca-file: "/etc/kubernetes/pki/front-proxy-ca.crt"
    kube-api-qps: "100"
    requestheader-allowed-names: ""
    kube-api-burst: "100"
  extraVolumes:
    - hostPath: "/etc/localtime"
      mountPath: "/etc/localtime"
      pathType: File
      readOnly: true
      name: localtime
    - name: k8s-certs
      hostPath: /etc/kubernetes/pki
      mountPath: /etc/kubernetes/pki
      readOnly: True
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
# 身份验证
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: "/etc/kubernetes/pki/ca.crt"
# 授权
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: "systemd"
cgroupRoot: "/"
cgroupsPerQOS: true
clusterDNS:
- "172.31.0.10"
clusterDomain: "cluster.local"
configMapAndSecretChangeDetectionStrategy: Watch
containerLogMaxFiles: 10
containerLogMaxSize: 20Mi
contentType: application/vnd.kubernetes.protobuf
cpuCFSQuota: true
cpuCFSQuotaPeriod: 100ms
cpuManagerReconcilePeriod: 10s
enableContentionProfiling: true
enableControllerAttachDetach: true
enableDebuggingHandlers: true
# Node 资源驱逐策略
evictionHard:
  imagefs.available: "15%"
  memory.available: "300Mi"
  nodefs.available: "10%"
  nodefs.inodesFree: "5%"
evictionMaxPodGracePeriod: 30
evictionPressureTransitionPeriod: 0s
evictionSoft:
  imagefs.available: "15%"
  memory.available: "512Mi"
  nodefs.available: "15%"
  nodefs.inodesFree: "10%"
evictionSoftGracePeriod:
  imagefs.available: 3m
  memory.available: 1m
  nodefs.available: 3m
  nodefs.inodesFree: 1m
evictionMinimumReclaim: {}
failSwapOn: true
cpuManagerPolicy: none
# Node 资源预留
enforceNodeAllocatable:
- pods
# kube Cgroups
# system Cgroups
eventBurst: 10
eventRecordQPS: 5
featureGates:
  RotateKubeletServerCertificate: true
fileCheckFrequency: 20s
hairpinMode: hairpin-veth
healthzBindAddress: 127.0.0.1
# kubelet健康检查端口
httpCheckFrequency: 20s
# 镜像删除策略
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 80
imageMinimumGCAge: 2m0s
iptablesDropBit: 15
iptablesMasqueradeBit: 14
kubeAPIBurst: 100
kubeAPIQPS: 100
makeIPTablesUtilChains: true
maxOpenFiles: 1000000
maxPods: 100
nodeLeaseDurationSeconds: 40
nodeStatusMaxImages: 50
nodeStatusReportFrequency: 1m0s
nodeStatusUpdateFrequency: 10s
oomScoreAdj: -999
podPidsLimit: -1
# 监听地址
address: 0.0.0.0
registryBurst: 20
registryPullQPS: 5
resolvConf: /etc/resolv.conf
rotateCertificates: true
# 只能设置为 false, 否则启动报错: panic: runtime error: invalid memory address or nil pointer dereference
runOnce: false
runtimeRequestTimeout: 15m0s
serializeImagePulls: false
serverTLSBootstrap: true
staticPodPath: "/etc/kubernetes/manifests"
streamingConnectionIdleTimeout: 4h0m0s
syncFrequency: 1m0s
tlsCipherSuites:
- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
- TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
- TLS_RSA_WITH_AES_256_GCM_SHA384
- TLS_RSA_WITH_AES_128_GCM_SHA256
volumePluginDir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
volumeStatsAggPeriod: 1m0s
AllowedUnsafeSysctls:
- "net.core.somaxconn"
- "kernel.msg*"
kernelMemcgNotification: false
protectKernelDefaults: false
topologyManagerPolicy: "none"
topologyManagerScope: "container"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: 0.0.0.0
healthzBindAddress: "127.0.0.1:10256"
metricsBindAddress: "127.0.0.1:10249"
clientConnection:
  acceptContentTypes: ""
  burst: 100
  contentType: application/vnd.kubernetes.protobuf
  qps: 100
clusterCIDR: "172.30.0.0/16"
configSyncPeriod: 10m0s
conntrack:
  maxPerCore: 32768
  min: 131072
  tcpCloseWaitTimeout: 1h0m0s
  tcpEstablishedTimeout: 24h0m0s
detectLocalMode: ""
enableProfiling: false
hostnameOverride: "172.21.139.219"
featureGates:
  RotateKubeletServerCertificate: true
mode: "ipvs"
iptables:
  masqueradeAll: false
  masqueradeBit: 14
  minSyncPeriod: 0s
  syncPeriod: 30s
ipvs:
  excludeCIDRs: []
  minSyncPeriod: 0s
  scheduler: "rr"
  # metalLB
  strictARP: true
  syncPeriod: 30s
  tcpFinTimeout: 5s
  tcpTimeout: 5s
  udpTimeout: 5s
nodePortAddresses: []
oomScoreAdj: -999
portRange: ""
winkernel:
  enableDSR: false
  networkName: ""
  sourceVip: ""
