- block:
  - name: 创建 kube-proxy 组件配置文件目录
    file:
      path: "{{ item }}"
      state: directory
      mode: 0644
    with_items:
    - "{{ addons_dir }}/kube-proxy"

  - name: 渲染 kube-proxy 配置文件
    template:
      src: "{{ item.src }}.j2"
      dest: "{{ item.dest }}"
      owner: "root"
      group: "root"
      mode: "0644"
    with_items:
      - { src: "kube-proxy/kubeproxy-cm.yml", dest: "{{ addons_dir }}/kube-proxy/kubeproxy-cm.yml" }
      - { src: "kube-proxy/kubeproxy-ds.yml", dest: "{{ addons_dir }}/kube-proxy/kubeproxy-ds.yml" }
  when:
  - skip_kube_proxy | bool
