
---
- name: Add a repository
  kubernetes.core.helm_repository:
    name: elastic-mirror
    repo_url: https://charts.softonic.io

- name: Update helm repo
  ansible.builtin.command: helm repo update

- name: Deploy latest version of ECK chart inside elastic namespace
  kubernetes.core.helm:
    kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
    name: elastic
    chart_ref: elastic-mirror/eck-operator
    release_namespace: elastic
    create_namespace: true
    wait: true
    atomic: true
    values:
      config:
        metricsPort: "7777"
      podMonitor:
        enabled: true
        labels:
          release: "{{ prometheus_stack_release_name }}"
          app: kube-prometheus-stack
        namespace: "{{ prometheus_stack_namespace }}"

- name: Wait for elastic pods become ready
  ansible.builtin.command: "kubectl wait --namespace=elastic --for=condition=Ready --all pods --timeout=600s"

- name: Create Elasticsearch
  kubernetes.core.k8s:
    kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
    state: present
    definition:
      apiVersion: elasticsearch.k8s.elastic.co/v1
      kind: Elasticsearch
      metadata:
        name: elasticsearch
        namespace: elastic
      spec:
        version: 8.6.1
        nodeSets:
        - name: default
          count: 1
          config:
            node.roles: [ data, master, ingest ]
            node.store.allow_mmap: false

- name: Create Kibana
  kubernetes.core.k8s:
    kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
    state: present
    definition:
      apiVersion: kibana.k8s.elastic.co/v1
      kind: Kibana
      metadata:
        name: kibana
        namespace: elastic
      spec:
        version: 8.6.1
        count: 1
        http:
          service:
            spec:
              type: ClusterIP
          tls:
            selfSignedCertificate:
              disabled: true
        elasticsearchRef:
          name: elasticsearch
          namespace: elastic

- name: Wait for elastic pods become ready
  ansible.builtin.command: "kubectl wait --namespace=elastic --for=condition=Ready --all pods --timeout=600s"

- name: Create Ingress for Kibana
  kubernetes.core.k8s:
    kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: kibana-ingress
        namespace: elastic
      spec:
        ingressClassName: nginx
        rules:
          - host: "{{ kibana_ingress_host }}"
            http:
              paths:
                - pathType: Prefix
                  path: "/"
                  backend:
                    service:
                      name: kibana-kb-http
                      port:
                        number: 5601
