- name: 所有 kube_cluster 节点加载依赖镜像
  when: inventory_hostname in (groups['kube_cluster'] | difference(groups['delete_masters']) | difference(groups['delete_nodes']) | unique)
  shell: >
    {% if container_runtime == 'docker' -%}
      docker load -i {{ cache_dir }}/images/all.tar.gz
    {% elif container_runtime == 'containerd' -%}
      ctr -n=k8s.io images import {{ cache_dir }}/images/all.tar.gz
    {%- endif -%}

- name: 加载 master 节点各组件镜像
  when: "inventory_hostname in (groups['kube_masters'] | difference(groups['delete_masters']))"
  shell: >
    {% if container_runtime == 'docker' -%}
      docker load -i {{ cache_dir }}/images/master.tar.gz
    {% elif container_runtime == 'containerd' -%}
      ctr -n=k8s.io images import {{ cache_dir }}/images/master.tar.gz
    {%- endif -%}

- name: worker 节点加载依赖镜像
  when: "inventory_hostname in (groups['kube_nodes'] | difference(groups['delete_nodes']))"
  shell: >
    {% if container_runtime == 'docker' -%}
      docker load -i {{ cache_dir }}/images/worker.tar.gz
    {% elif container_runtime == 'containerd' -%}
      ctr -n=k8s.io images import {{ cache_dir }}/images/worker.tar.gz
    {%- endif -%}
