---
- name: 所有 kube_cluster 节点创建所需目录
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
    mode: 0644
  with_items:
  - "{{ ansible_env.HOME }}/.kube/"
  - "{{ kubernetes_etc_dir }}"
  - "{{ manifest_dir }}"
  - "{{ cni_etc_dir }}"
  - "{{ systemd_service_dir }}/kubelet.service.d"
  - "{{ kubelet_data_dir }}"

- name: 所有 kube_cluster 节点渲染 kubelet.service
  ansible.builtin.template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
  - { src: "kubelet/kubelet.service", dest: "{{ systemd_service_dir }}/kubelet.service", mode: "0644" }

- name: 所有 kube_cluster 节点渲染 kubelet.service.d 配置文件
  ansible.builtin.template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
  - { src: "kubelet/10-kubeadm.conf", dest: "{{ systemd_service_dir }}/kubelet.service.d/10-kubeadm.conf" }
  - { src: "kubelet/00-container-runtime.conf", dest: "{{ systemd_service_dir }}/kubelet.service.d/00-container-runtime.conf" }
  - { src: "kubelet/00-cgroup.conf", dest: "{{ systemd_service_dir }}/kubelet.service.d/00-cgroup.conf" }

- name: 配置 Kubelet 开机自启
  ansible.builtin.systemd:
    daemon_reload: true
    name: kubelet
    enabled: true

## 1.15.12 匿名用户报错：
# https://happywzy.top/k8s-master-jie-dian-notready/
# kubectl create clusterrolebinding test:anonymous --clusterrole=cluster-admin --user=system:anonymous
## 安装 flannel 失败：
# rm -f /etc/cni/net.d/99-containerd-net.conflist
# systemctl stop kubelet && ip link del cni0 && systemctl restart kubelet
- name: 所有 kube_cluster 节点渲染相关配置文件
  when: kube_version is version('1.17.0', '<=')
  ansible.builtin.template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
  # 不需要创建,static pod 会初始化失败
  - { src: "cni-plugin/10-containerd-net.conflist", dest: "{{ cni_etc_dir }}/99-containerd-net.conflist" }
