- name: 创建 etcd 数据目录
  file: name={{ item }} state=directory mode=u=rwx,g-rwx,o-rwx
  with_items:
    - "{{ etcd_data_dir }}"

- name: 创建 etcd 数据备份目录
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
    - "{{ etcd_data_bak_dir }}"

- name: 设置 etcd 数据备份, 每天凌晨3点备份
  cron:
    name: "create etcd data backup"
    minute: "0"
    hour: "3"
    job: "etcd_cron.sh -c 4 -d {{ etcd_data_bak_dir }} &>/dev/null 2>&1"

- name: restore etcd data
  when: inventory_hostname in (groups['kube_cluster'] | difference(groups['delete_masters']) | difference(groups['delete_nodes']) | unique)
  include_tasks: restore.yml
